services:
  bootstrap:
    build: . 
    image: d7024e-node:latest
    restart: "no"
    environment:
      - NODE_PORT=8000
      - IS_BOOTSTRAP=true
      - ADVERTISE_HOST=bootstrap
    ports:
      - "8000:8000"
    networks:
      - kademlia_network
    stdin_open: true
    tty: true

  node:
    build: . 
    image: d7024e-node:latest
    restart: "no"
    environment:
      - NODE_PORT=8001
      - BOOTSTRAP_ADDR=bootstrap:8000
    depends_on:
      - bootstrap
    networks:
      - kademlia_network
    stdin_open: true
    tty: true

networks:
  kademlia_network: