services:
  bootstrap:
    build: . 
    image: d7024e-node:latest
    environment:
      - NODE_PORT=8000
      - IS_BOOTSTRAP=true
      - ADVERTISE_HOST=bootstrap
      - DOCKER_ENV=true
    ports:
      - "8000:8000"
    networks:
      - kademlia_network

  node:
    build: . 
    image: d7024e-node:latest
    environment:
      - NODE_PORT=8001
      - BOOTSTRAP_ADDR=bootstrap:8000
      - ADVERTISE_HOST=node
      - DOCKER_ENV=true
    depends_on:
      - bootstrap
    networks:
      - kademlia_network

networks:
  kademlia_network: